language: php

matrix:
  include:
    - php: 7.0
    - php: 7.1
    - php: nightly
  fast_finish: true
  allow_failures:
    - php: nightly

sudo: false

cache:
  directories:
    - $HOME/.composer

install:
  - composer install --prefer-source

script:
  - vendor/bin/peridot specs/ -r emoji
  - vendor/bin/peridot specs/ -r clover-code-coverage

after_success:
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN

